# Generated by Django 4.1 on 2022-09-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
