# Generated by Django 4.1 on 2022-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderWeb', '0002_alter_edge_targetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='targetId',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='initialValue',
            field=models.FloatField(default=1),
        ),
    ]
