# Generated by Django 4.1 on 2022-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderWeb', '0003_alter_edge_targetid_alter_node_initialvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edge',
            name='isPercentage',
            field=models.BooleanField(default=False),
        ),
    ]
