# Generated by Django 4.1 on 2022-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0003_alter_edgemodel_sourceamount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgemodel",
            name="sourceAmount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="edgemodel",
            name="sourcePercentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="edgemodel",
            name="sourceRemainingBalance",
            field=models.BooleanField(default=False),
        ),
    ]
