# Generated by Django 4.1 on 2022-08-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0004_edge_amount_edge_ispercentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edge",
            old_name="amount",
            new_name="sourceAmount",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="isPercentage",
        ),
        migrations.AddField(
            model_name="edge",
            name="sourcePercentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="edge",
            name="sourceRemainingBalance",
            field=models.BooleanField(default=False),
        ),
    ]
