# Generated by Django 4.1 on 2022-09-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0004_alter_edgemodel_sourceamount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edgemodel",
            name="user",
        ),
    ]
