# Generated by Django 4.1 on 2022-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SpiderWeb", "0005_remove_edgemodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodemodel",
            name="user",
        ),
    ]
